//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DitProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalSupportCenter
    {
        public int Id { get; set; }
        public Nullable<int> IdDorm { get; set; }
        public Nullable<int> IdInstit { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
    
        public virtual Dorms Dorms { get; set; }
        public virtual Institutions Institutions { get; set; }
    }
}
